### ISSUE TITLE
Types are not recognized when imported from locally declared modules

### ISSUE THREAD

**Issue by vincaslt** [flowtype/flow-for-vscode#98]
So I am trying to declare modules with type declarations for separate parts of my app, and when trying to import them, they are not recognized (var:any). I'm following: https://flowtype.org/docs/declarations.html#declaring-modules

`.flowconfig`:

```
[ignore]

[include]

[libs]
src/flowtypes/

[options]
```

`src/flowtypes/index.js`:

```
declare module 'fl-types' {
  declare class ActionType {
    type: string,
    payload: ?Object
  }
}
```

`src/flowtypes/flashcard.js`:
```
declare module 'fl-flashcard' {
  declare class CardType {
    word: string,
    meaning: string
  }

  declare class LastAnswerType {
    word: string,
    answer: string,
    status: boolean
  }

  declare class PropTypes {
    card: CardType,
    submit: Function,
    lastAnswer: ?LastAnswerType
  }

  declare class StateType {
    word: string,
    meaning: string,
    lastAnswer: ?LastAnswerType
  }
}
```

Now when I'm trying to import these type definitions, they are never recognized:

```
// @flow
import type { ActionType } from 'fl-types'
import type { LastAnswerType, CardType, StateType } from 'fl-flashcard'

export const initialState: StateType = {
  word: 'a',
  meaning: 'b',
  lastAnswer: null
}
```

It says the type is incompatible, and hovering on any of the types simply shows `any`, which leads me to believe that flow extension doesn't understand the types from definitions.

Maybe I'm doing something wrong?

**Comment by orta** [comment]
Have you looked at what `flow autocomplete` responds with at that character to see if this is a flow issue?

**Comment by mosesoak** [comment]
Same issue. I have found that removing the word `type` from the import fixes it – but that is a bug in this plugin that should be fixed!

I also had to add `/index` to the path to fully make it work.

Unfortunately even with these workarounds, Flow itself does not currently work. https://github.com/facebook/flow/issues/3520

**Comment by fignuts** [comment]
I'm having the same issue. Imported types don't work in vscode.

**Comment by t2** [comment]
Did anyone ever get this working? I cannot import types in latest VS Code and latest flow.

**Comment by v0lkan** [comment]
## Bottom line up front:

Things work pretty well in insider version with the recent flow version (0.62.0)

So works for me ¯\_(ツ)_/¯ 

The only mild annoyance is, it still shows “any” when I hover over some of the members; but flow checks and realtime warnings, and squiggly red underlines etc work just fine.
(And when I CMD+hover (instead of regular hover) that `any` fixes itself and I see the entire flow annotation as declared in flowtypes/index.js — so that bug is kinda cosmetic and I’ve habituated to CMD+hover so I don’t feel it at all :) )

## The Details

> Did anyone ever get this working? I cannot import types in latest VS Code and latest flow.

Cannot reproduce on Visual Studio Code insider with the latest flow and official flowtype plugin.

Here are my files:

.flowconfig:

```text
[ignore]
./node_modules

[include]
./lib/**/*
./src/**/*

[libs]
./flow-types

[lints]

[options]

[strict]
```

flow-types/index.js

```javascript
declare module 'slytherin-types' {
  declare type DragEventMeta = {
    start: { clientX: number, clientY: number, left: number, top: number },
   dragging: boolean,
   tickId: number,
   elm: () => (HTMLElement | null),
   dragClassName?: string,
   isDraggable: (elm: HTMLElement) => boolean
  };

 declare type DragInitializationOptions = {
   dragClassName?: string,
   dragHandleClassName?: string
 };

 declare type DraggablePredicate = (elm: HTMLElement) => boolean;
}
```

sample usage in file:

```javascript
import type { DragEventMeta, DragInitializationOptions, DraggablePredicate } from 'slytherin-types';
```

code snippet to check if it errs out:

```javascript
const init = (elm: HTMLElement, options: DragInitializationOptions): void => {
  if (!elm) {
    return;
  }

  activeDraggable = elm;

  options.bazinga; // <= this errs because bazinga is not a member of DragInitializationOptions
```

Sample output after executing `flow`:

```text
slytherin> flow
Error: lib/index.js:52
 52:   options.bazinga;
               ^^^^^^^ property `bazinga`. Property not found in
 52:   options.bazinga;
       ^^^^^^^ DragInitializationOptions

Found 1 error
```

The error dialog VS Code gives when I hover the variable.

```text
[flow] property `bazinga` (Property not found in DragInitializationOptions)
any
```

flow version: 

```text
slytherin> flow version
Flow, a static type checker for JavaScript, version 0.62.0
```
I am using `flow` from a global NPM install.

The code that I tested VSCode/Flow is vailable at:

https://github.com/jsbites/slytherin

Hope that helps.

**Comment by Mayank1791989** [comment]
Not happening now may be some old bug which is fixed already.
